name: examples

on: [push]

env:
  NILE_DEVELOPER_EMAIL: ${{ secrets.NILE_DEVELOPER_EMAIL }}
  NILE_DEVELOPER_PASSWORD: ${{ secrets.NILE_DEVELOPER_PASSWORD }}

jobs:

  multi-tenancy:

    needs: create-envfile

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NILE_URL: https://prod.thenile.dev:443
          envkey_NILE_WORKSPACE: foo
          envkey_NILE_DEVELOPER_EMAIL: ${NILE_DEVELOPER_EMAIL}
          envkey_NILE_DEVELOPER_PASSWORD: ${NILE_DEVELOPER_PASSWORD}
          envkey_NILE_ORGANIZATION_NAME: sac-norad
          envkey_NILE_ENTITY_NAME: SkyNet
          directory: multi-tenancy
          file_name: .env
          fail_on_empty: false

      - name: Set node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: yarn install
        working-directory: multi-tenancy
        run: yarn install --no-lockfile

      - name: yarn setup
        working-directory: multi-tenancy
        run: |
          timeout 15s yarn start

      - name: yarn test-setup
        working-directory: multi-tenancy
        run: yarn test-setup
