name: examples

on: [push]

env:
  NILE_DEVELOPER_EMAIL: ${{ secrets.NILE_DEVELOPER_EMAIL }}
  NILE_DEVELOPER_PASSWORD: ${{ secrets.NILE_DEVELOPER_PASSWORD }}

jobs:

  multi-tenancy:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: yarn install
        working-directory: multi-tenancy
        run: yarn install --no-lockfile

      - name: yarn setup
        working-directory: multi-tenancy
        run: |
          timeout 15s yarn start

      - name: yarn test-setup
        working-directory: multi-tenancy
        run: yarn test-setup
